name: Test Coveralls

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v4
      
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - run: npm install
      
      - run: npm test -- --coverage
      
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
